# Generated by Django 4.2.1 on 2025-01-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myresume',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='myresume',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='myresume',
            index=models.Index(fields=['-time_create'], name='myresume_my_time_cr_ab920b_idx'),
        ),
    ]
