# Generated by Django 4.2.1 on 2025-01-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0002_alter_myresume_options_myresume_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myresume',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
