# Generated by Django 4.2.1 on 2025-01-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0003_alter_myresume_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myresume',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
    ]
