# Generated by Django 4.2.1 on 2025-01-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0005_category_myresume_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myresume',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myresume.category'),
        ),
    ]
