# Generated by Django 4.2.1 on 2025-02-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0008_photo_myresume_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
